project:
  type: website
  output-dir: docs

website:
  title: "Birding Tools"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Locations.qmd

format:
  html:
    theme: superhero
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#EEF6F4"
    linkcolor: "#3B56ED"
    monofont: courier new
    css: styles.css
    toc: true



